spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passdb?serverTimezone=Europe/Minsk&useSSL=false
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    username: bot_user
    password: dothisfrom2022
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update